name: Deploy to Firebase

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
            ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2.3.1
        with:
          node-version: 16

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: echo $FIREBASE_TOKEN > $HOME/firebase-token
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: List Contents of dist/chat-mignon
        run: ls -R dist/chat-mignon        

      - name: Deploy to Firebase
        run: firebase deploy --token $(cat $HOME/firebase-token) --project chatmignon-72a72

