name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true 

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.0.5

      - name: Build and Deploy
        run: |
          npm install
          ng build --prod
          firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
